version: "2.2"
 
services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
      - 13306:13306
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_SCHEMA_PATH=models
      - CUBEJS_DB_TYPE=mongobi
      - CUBEJS_DB_HOST=supportable-nonprod-biconnector.pfmm0.mongodb.net
      - CUBEJS_DB_PORT=27015
      - CUBEJS_DB_NAME=sup-dev
      - CUBEJS_DB_USER=application_user
      - CUBEJS_DB_PASS=0agOMsyJVVgl1bIX
      - CUBEJS_DB_SSL=true
    volumes:
      - .:/cube/conf